### ISSUE TITLE
[UI/UX] - Position Detail - Transfer outcome tokens

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#191]

**Comment by gabitoesmiapodo** [comment]
@cmalfesi 

I'd need some extra info for this.

What fields do we need for this form?

I'm thinking maybe send to address, amount... anything else?

**Comment by mariano-aguero** [comment]
We need:
- A modal that...
- Display the balance
- Add a Max button
- Add a bigNumberInput to set the amount to transfer
- Display errors or warnings
- Submit button
- Display spinner for the mining transaction and success

**Comment by mariano-aguero** [comment]
Look like this ...
![Peek 16-09-2020 11-24](https://user-images.githubusercontent.com/1144028/93350678-468c0200-f80f-11ea-83de-bd1586a571ab.gif)

**Comment by mariano-aguero** [comment]
@elena-zh  to take into account, this bug was introduced I think in this PR (https://github.com/gnosis/conditional-tokens-explorer/pull/236/files) , I also added an small fix for this, Please check this is working properly. Thanks!

![Peek 18-09-2020 13-53](https://user-images.githubusercontent.com/1144028/93625449-5a269c80-f9b8-11ea-8c73-bb9a82c50484.gif)

**Comment by elena-zh** [comment]
The changes look good to me.
