### ISSUE TITLE
[FE] Impossible to create positions using custom collaterral (BAT)

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#242]
**Steps:** 
1. Create a condition
2. Open the Split Position page
3. Select custom collateral (I select BAT - contract address: 0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99), unlock the contract
4. Fill in all the required fields, press on Split, confirm the action in Metamask

**AR:** each transaction is finished with FAIL status --> positions are not displayed in the Positions list
https://rinkeby.etherscan.io/tx/0xa68fff0e169ac0cf8050aceef9092464003b9736d58f79d5a2662c751405ca9e
https://rinkeby.etherscan.io/tx/0x9d0d894534e81a0016e783050208c5f670cad88ce45ffc0d393e30aa7adef158
https://rinkeby.etherscan.io/tx/0x1240638d91ac805fb0134f812f0e9ae5c0fe39c0f604ff7e5897bfea2cfbc9eb

**ER:** positions should appear in the Positions list

**Comment by hpmaxi** [comment]
This seems to happen only with BAT, I think is related to some method inside the ERC20 contract that is failing. But also that failure isn't handled by the catch block for some reason, so `positionsIds` is built and shown with status.isSuccess true.

**Comment by mariano-aguero** [comment]
> This seems to happen only with BAT, I think is related to some method inside the ERC20 contract that is failing. But also that failure isn't handled by the catch block for some reason, so `positionsIds` is built and shown with status.isSuccess true.

Maybe but doesn't hjave all the common methods for an ERC20 ? Did you know what method trigger this exception?

**Comment by hpmaxi** [comment]
Only transfer and transferFrom are used in CT contract. I tried with others ERC20 like FAU, and it worked.

**Comment by hpmaxi** [comment]
I tried to calculate the revert reason with this gist https://gist.github.com/spalladino/7bce4a27626fc3327731f3ddb9f7587f but I had no luck, I guess it is not related to `require` logic of CT and instead is have to do with the BAT contract in rinkeby as we thought in the beginning.

**Comment by mariano-aguero** [comment]
This is a failed transaction
https://dashboard.tenderly.co/tx/rinkeby/0x89b5113afcbef3befd429f50796c536266c72effadbc113a8a0a007bb3a1d37c/debugger

The result says that the contrat doesn't have allowance (And is not true), also I sended some tokens with my wallet to the contract, and works!! So the problem seems to be in the contract, maybe is not returning true in the revert action

The transfer transacion
https://rinkeby.etherscan.io/tx/0xb8191d6ae2cf8470db6effe2cb9f9446ebf7adff6cb5a72b0caeb46af96d9da0

I think we can close this, probably we can use BAT with the CTE
