### ISSUE TITLE
Partition section - Edit partition bugs

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#253]
Related to #237 , #66 , #67 , #65 , #160

1. Empty rows are displayed in the section when drag and drop all the outcomes and then click on the reset button (see the video)
https://drive.google.com/file/d/1DJeNOQ5emlvRIEjTfz2HK1-7UDe_p-ta/view

2. Empty rows are displayed in the section when replace an outcome into Outcomes section by **clicking on the outcome circle** and then click on the reset button 

3. The system allows to save a partition with only one collection in it: repeat steps 1 or 2 of the current issue, an then, then there is only one outcome and 1 empty line, click on the Save button (see the video). The transaction for positions creating will be finished with failure
https://drive.google.com/file/d/1-hYTJCH9QatnUD1HNiUX7jaDeXPk9PkO/view

4. Numbers do not fit the circle area when a condition contains outcomes more than 100 outcomes (3-digits outcomes)
![3 nubers outcomes.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5498cd2b-4716-45c1-beaf-7c8a98fadb30)

5. The edited partitioning before login is not saved after a user logs in (see the video) Note: the issue with amount field on the video is described here: #252
https://drive.google.com/file/d/1HscxRWRKrSb8_e1AOgjIt_QYhaMJo04-/view

6. Bin icon is still displayed when drag and drop a position (should not be displayed according to the mock-up (https://zpl.io/aR5Z76K)

7. a Circle in the New collection prevoew field should be in red when hover a mouse on it according to the mock-up (https://zpl.io/aR5Z76K)
![red.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2c295e7c-c007-43b9-8db1-f96ebfa05440)

8. No horizontal lines should be displayed in the partition when it contains a lot of outcomes, placed one after another according to the mock-up (https://zpl.io/aR5Z76K)

9. 'Move' and 'Bin' icons should be top-aligned when outcomes exceed 1 line (mock-up https://zpl.io/aR5Z76K)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/49a10f9d-a164-4458-9cd5-a8ed9774c13e)

10. New collection preview should contain the lines between the outcomes according to the mock-up https://zpl.io/V039zl9
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0404bb47-209c-4257-87fe-81ca0e0af0cd)

11. There is no confirmation before removing New Collection Preview. It should be according to the mock-up https://zpl.io/a3WXQZx
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/20d0331c-7fc3-4a4f-be57-2de464e92449)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/122ac389-ec67-4f68-9cd6-f553b30ce3e4)

12. It would be nice not to order outcommes in ASC order when move them into the New Collection Preview field (it will be diffiecuit to a User to create a 'right' collection). See the video
https://drive.google.com/file/d/14ilfd1Fh2HQwusey4mMTmwQLUj0homEA/view

13. No ability to create a separate collection using drag and drop functionality for an outcome 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6b1ec822-7058-45d1-bcdd-8a2e3df6a234)

**Comment by gabitoesmiapodo** [comment]
**Note:** I'm creating a draft PR [here](https://github.com/gnosis/conditional-tokens-explorer/pull/263) so we have a preview available to test this if necessary.

@elena-zh A lot of these "issues" were intended, but you had no way of knowing that, of course. There's a long list of changes and some explanation about them here: https://github.com/gnosis/conditional-tokens-explorer/issues/160#issue-478165579 (you don't need to go through all of it, but those were my reasons to do what I did).

Some of the issues you found are valid too, so I fixed them. 

I'll update the designs where necessary (I thought I did, but it seems I didn't...), and explain everything it's needed to be explained.

**Details below:**

. Issues 1 / 2 / 3 / 5: @mariano-aguero  will look into them.
.`4. Numbers do not fit the circle area when a condition (...)` ugh, completely forgot to test this. It looked fine in the designs, but it's not rendered so well by the browser. I had to implement a few tweaks to fit the numbers: circles are a bit bigger now (27px), font is a little smaller (13px), font weight is 600 instead of 700, and I reduced letter spacing a bit. It should be fixed now:

![Screen Shot 2020-09-15 at 16 36 13](https://user-images.githubusercontent.com/4015436/93256446-c19edb00-f771-11ea-8aee-5fae5226793b.png)
. `6. Bun icon is still displayed when drag and drop a position (...)` I'm not sure I understand this one, but are you referring to the trash icon? If that's the case, I decided to leave it, as implementing it just complicated the code and UX  resulted more confusing too. Updated the design to reflect this.
. `7. a Circle in the New collection prevoew field (...)` That's an oversight on my part, design should be updated now.
. `8. No horizontal lines should be displayed in the partition (...)` That's correct. I implemented as it is now because I thought it could make more sense this way, but I'm still unsure... Anyways, I modified it to look as it is in the design, maybe it's better now:

![Screen Shot 2020-09-15 at 17 05 28](https://user-images.githubusercontent.com/4015436/93259155-c6fe2480-f775-11ea-80ae-75573eedceac.png)
. `9. 'Move' and 'Bin' icons should be top-aligned when outcomes exceed (...)` "Move" icons are okay where they are now (that's intentional), but you are correct about the "Remove" icons. Fixed.
. `10. New collection preview should contain the lines between the outcomes (...)` That's an error in the design. Updated accordingly.
. `11. There is no confirmation before removing New Collection Preview. (...)` It seems I placed the note in an ambiguous place, but there should be confirmations only when bulk removing items from the original list. Design's updated to clarify this.
. `12. It would be nice not to order outcommes in ASC order when move them into the New Collection Preview (...)` I think I remember somebody asked for it to be that way (maybe @lmcorbalan ). I don't have an strong opinion about this, but maybe I'd leave it as it is just to keep consistency.
. `13. No ability to create a separate collection using drag and drop functionality for an outcome (...)` Yeah, that's not the intended workflow. But I think we can consider and implement it if there's enough demand.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , thanks for the explanation. I went trough the through all the changes in the pull-request. ##4, 8, 9 look good to me. 
Regarding to the p.12: I saw the comment to order the outcomes asc only for the the 1st field (Outcomes) (https://github.com/gnosis/conditional-tokens-explorer/pull/160#issuecomment-687113494), but not for the 2nd one (where a user actually 2 'builds' a collection). That is why I have mentioned this point.

p.13: should I need to create a separate task for this issue?

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

Maybe we should ask @hpmaxi and @mariano-aguero what they think about p.12? I'm fine either way, but I'd prefer we have a consensus about it.

About p.13: It's not really an issue (it wasn't planned for it to work this way). I'd like to have some user / customer feedback before implementing more changes there (this feature could be changed completely based on that... or not), but maybe you could create an issue for that as a suggestion / enhancement and we'll see what we do about that in the future.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I have created a low-priority enhancement for the future #278. 

BTW, I have noticed that numbers are a bit right-aligned in outcomes circles. Is it possible to fix it and make then center-aligned? 
![rignt -aligned](https://user-images.githubusercontent.com/70885163/93468457-ae1d7c80-f8f7-11ea-95bc-c5e0b4c34144.jpg)

**Comment by gabitoesmiapodo** [comment]
@elena-zh It should look a bit better now.

![Screen Shot 2020-09-17 at 11 43 50](https://user-images.githubusercontent.com/4015436/93487072-4e18dd00-f8db-11ea-8060-60b90a5edf9f.png)

**Comment by elena-zh** [comment]
@gabitoesmiapodo , yes, looks much better now. Thank you!

**Comment by mariano-aguero** [comment]
@elena-zh Points 1, 2 and 3 was fixed, working on 5

**Comment by mariano-aguero** [comment]
> @elena-zh Points 1, 2 and 3 was fixed, working on 5

Created an issue for the point 5 https://github.com/gnosis/conditional-tokens-explorer/issues/292

**Comment by elena-zh** [comment]
Hi @gabitoesmiapodo , @mariano-aguero , 

I have checked all the available fixed in Dev. 
All the changes look good to me, but still we do not have a consensus reached on the p.12.

>  I saw the comment to order the outcomes asc only for the the 1st field (Outcomes) (https://github.com/gnosis/conditional-tokens-explorer/pull/160#issuecomment-687113494), but not for the 2nd one (where a user actually 2 'builds' a collection)

Also, numbers are still a bit right-aligned in outcomes circles. @gabitoesmiapodo , could you please check whether your latest changes on this were deployed to Dev? 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ff5ddd61-2e66-4671-bcec-079313366221)

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

I say we leave p12 as it is. Outcomes' order is not really important, and sorting outcomes makes it easier for the user to visually find them.

Regarding the typography this is what I'm getting on `/develop` 

![Screen Shot 2020-09-21 at 10 37 39](https://user-images.githubusercontent.com/4015436/93773958-11a8f200-fbf7-11ea-9c9a-3e44423e1a3a.png)


If you're still having issues, maybe you could create a new issue detailing browser, OS, etc. and I'll have a look (I'm thinking maybe fonts are not downloading to your computer).

**Comment by elena-zh** [comment]
@gabitoesmiapodo , thanks for the explanation. 
Sure, there might be issues with screen resolution, screen width, scale, browser and its version, and etc. 
I will try to catch the details and then will post an issue. 
For now, I will close the current ticket as all the rest issues are resolved here.
