### ISSUE TITLE
[FE] Redeem positions: Incorrect field's values for the  RESOLVED CONDITION ID/ REDEEMED POSITION PREVIEW 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#313]
**See the pic:** 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b1a3a85e-6a38-43a1-a738-e7a6b81b9f45)

**Expected Result:** 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5d708bf3-ba6e-4494-94d1-1ec285dffbca)

Mock-up: https://zpl.io/agYL4B1

**Comment by hpmaxi** [comment]
This can be closed, I tested many cases here https://gist.github.com/hpmaxi/e88f0adcb07c944d821bf862d53c0359 .

Condition resolved id is wrong in the mockup so it is ok in the app.  The preview is OK for cases when you receive the original collateral instead of another position, anyway I've tested a few cases.
