### ISSUE TITLE
[FE] Fix sorting in conditions and positions tabs

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#340]
It's not immediately obvious what order the items in the conditions and positions tabs are sorted in.
As a new user, I would assume they are sorted in reverse chronological order, newest first. When, in fact, they are sorted in ascending order by condition ID.

Condition ID is a pseudorandom hash, so it's meaningless to sort them in descending order.

This brings up an interesting issue. There are five columns currently in the conditions tab and sorting by any of them is pretty meaningless (at least without [richer search](https://github.com/gnosis/conditional-tokens-explorer/issues/337)).

In the conditions tab, we should:
1. disable sorting by conditionID, reporting address, and question ID.
2. add a "creation date" column and default to sorting the list by creation date in reverse chronological order.
3. add a total value locked (TVL) column and enable sorting by this column.
4. add an "oracle" column

In the positions tab, we should:
1. disable sorting by position ID
2. add a "creation date" column and default to sorting the list by creation date in reverse chronological order.
3. add an "oracle" column
4. add a "condition" ID column
5. add a "question ID" column

**Comment by gabitoesmiapodo** [comment]
Maybe we shouldn't disable sorting by ID? Maybe it's not useful for me, but it is for somebody else. Also it's already implemented, so it's basically free.

Agreed on adding a more meaningful search / filtering feature (that's high in my list of TODOs, I'm going to work on that next).

Regarding the creation date, I think @mariano-aguero is working on that here https://github.com/gnosis/conditional-tokens-explorer/issues/208

**Comment by auryn-macmillan** [comment]
Can you think of a scenario where it would be useful to sort by condition ID? 
I can't.

I agree that it's free / more work to take it out than leave it in, so I don't think it's high priority to disable it. But I don't think anyone will use it.

**Comment by gabitoesmiapodo** [comment]
> Can you think of a scenario where it would be useful to sort by condition ID?

Not really haha 😄  Same for "Question Id"

I think the guys implemented it just because it's really easy to do so.

Maybe sorting by "Reporting Address" could be useful though, but it will probably not be useful anymore when we implement better search and filtering.

**Comment by cag** [comment]
Hey, I don't think totalValueLocked is an easy ask, since it requires a price oracle, and may not be well defined as well. The price oracle is somewhat possible and introduces complexity, but the well-definedness of this concept may be a permanent blocker.

Consider positions derived from condition ab with outcome slots[a, b] and condition xy with outcome slots [x, y]. Let's say you have $10 in collateral. Split $5 into $5:a and $5:b, and condition ab has $5 of totalValueLocked. Merge it back, and you'd remove the totalValueLocked for condition ab. Similarly for condition xy.

The problem comes when you have deeper splits. Let's say you split $5 into $5:a and $5:b, then split $5 into $5:x and $5:y. Your TVL for ab is $5, and your TVL for xy is $5 as well. Then you split $5:x into $5:a&x, $5:b&x. Is your TVL for xy still $5? What about ab? If you don't touch these values, but then split $5:y into $5:a&y, $5:b&y, you can then merge those four positions into $5:x and $5:y, giving you a total of $10:x and $10:y, corresponding to $10 TVL for ab. When did the $5 TVL for xy move into ab?

**Comment by auryn-macmillan** [comment]
I'm not sure I understand the complexity here.

To me it seems quite simple, TVL is the total amount of underlying collateral that has been split in a condition. We could do a simple implementation without pricefeeds, in which case we're just sorting/filtering by the number of collateral tokens. Or, if we can get a price feed, then we can properly compare the TVL of different collaterals.

I never suggested that we should calculate TVL for positions.

**Comment by elena-zh** [comment]
Verified. 
Some notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/493#issuecomment-714352590)
