### ISSUE TITLE
[FE] Add more information to condition and position details

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#355]
In [this issue](https://github.com/gnosis/conditional-tokens-explorer/issues/340), I mentioned a few columns that would be great to add to the list views.

That information should also be added to the details view.

In the conditions details, we should add:
- creation date
- creator address
- Total Value Locked
- Link to any Omen markets for this condition
- Resolution details (for conditions that have been resolved)

In the positions details, we should add:
- creation date
- oracle address / name
- question ID
- total value locked
- Collateral token address
- Wrapped outcome token address
- Resolution details (for positions whose conditions have been resolved)

**Comment by elena-zh** [comment]
Verified. 
Resolution details to positions and Total Value Locked will be added in #526 
Several minor issues are found: 
#538 Display oracle = realit.oi for a position when it belongs to an omen condition
#539 Show a question text instead of a question id on a positions/conditions lists for Omen condition
