### ISSUE TITLE
[FE] Improve merge UX

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#358]
When merging a position we should:
- group positions that can be merged, in the select positions Dialogue.
- automatically populate the condition ID (if a position is built from a combination of conditions, user should be able to select one of the conditions)

![Screen record from 2020-09-24 16 41 38](https://user-images.githubusercontent.com/8453294/94198209-f05d3580-fe84-11ea-85f6-2b94662aabb5.gif)

**Comment by auryn-macmillan** [comment]
automatically populate the condition ID (if a position is build from a combination of conditions, user should be able to select one of the conditions) in the "redeem position" tab.

**Comment by gabitoesmiapodo** [comment]
@auryn-macmillan 

I've been working on this. It seems this workflow needed some re working, and the new search / filter features make this easier for everyone and allows us to get rid of the select position / condition modals (which turned out to be confusing for the users and additionally are on the spaghetti code side of things right now...).

I know this issue is for Merge / Redeem, but it kind of affects everything else, so I changed things for a few extra sections.

Let me know what you think, and if you are OK with these I'll create an epic to modify these sections.

![28- CTEAF Merge Positions (b)](https://user-images.githubusercontent.com/4015436/96470709-f2f14780-1204-11eb-9c54-29cebecf7fc8.png)
![29- CTEAF Redeem Positions (b)](https://user-images.githubusercontent.com/4015436/96470725-f7b5fb80-1204-11eb-9cd1-7658a53cf2f5.png)
![30- CTEAF Report Payouts (b)](https://user-images.githubusercontent.com/4015436/96470731-f84e9200-1204-11eb-85d1-2b548018ab62.png)
![31- CTEAF Split Position (b)](https://user-images.githubusercontent.com/4015436/96470735-f8e72880-1204-11eb-83c6-592a7c351b2c.png)
![31- CTEAF Filters - Alternative View](https://user-images.githubusercontent.com/4015436/96470746-fbe21900-1204-11eb-8c37-5bf02d2b50f3.png)

**Comment by gabitoesmiapodo** [comment]
Updated the designs above.

Also available on 

https://zpl.io/VQkAzP9 
https://zpl.io/VYed9Wn 
https://zpl.io/beQ874P 
https://zpl.io/adgm8zL 
https://zpl.io/bAL6zWx

**Comment by auryn-macmillan** [comment]
> Updated the designs above.
> 
> Also available on
> 
> https://zpl.io/VQkAzP9
> https://zpl.io/VYed9Wn
> https://zpl.io/beQ874P
> https://zpl.io/adgm8zL
> https://zpl.io/bAL6zWx

I can't see the zepelin files, most of it looks good to me.
The only thing that jumps out as a concern is the merge tab where it says "Dai" in the amount input box.
I guess it should say what you are merging into, which in the example is not Dai because only two of the boxes are selected.
![image](https://user-images.githubusercontent.com/8453294/96916641-d0199a00-1475-11eb-94ba-84e57c253a7d.png)

**Comment by gabitoesmiapodo** [comment]
@auryn-macmillan 

>The only thing that jumps out as a concern is the merge tab where it says "Dai" 

Ah, yes, you're right. Probably a leftover from something I copied.  I don't think it's even in the app, but I'll check.

So, if everything else is OK, I'll create an epic, issues, etc.

**Comment by gabitoesmiapodo** [comment]
Moved to a new issue in https://github.com/gnosis/conditional-tokens-explorer/issues/510
