### ISSUE TITLE
UI - add an ability to close Page settings dropdown by clicking outside its area

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#767]
Related to #725

This is not intuitively understandable to press once again on the Page Settings option in order to close the dropdown. 
So, when a dropdown is opened, and a user has not pressed on the Apply/Page Settings option, it will be displayed an eternity, even if positions list if reloaded
![Screenshot_3.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fdd57e93-aeaf-4748-a8c7-38632dba604b)

So it would be nice to add a possibility to close Page settings dropdown by clicking outside its area (and do not apply the changes to grid in this case)

**Comment by gabitoesmiapodo** [comment]
@elena-zh This section will be mostly reworked and this functionality discarded when we implement this https://www.figma.com/file/NKdZKp1kKzwW2fiJrD3n05/CTE-UI-update?node-id=25%3A602

It's not worth it to put more work into this unless it's not working / broken (that's why we didn't replicate the functionality on the Condition's list).

**Comment by mariano-aguero** [comment]
@elena-zh I think this is working on develop

**Comment by gabitoesmiapodo** [comment]
@elena-zh @mariano-aguero Yeah, it should have been fixed here https://github.com/gnosis/conditional-tokens-explorer/pull/776/commits/f57128b2e416e8827abb5db077196beb886591fe
